### ISSUE TITLE
Can't install from Chrome Web Store

### ISSUE THREAD

**Issue by agungyuliaji** [banyan/github-story-points#4]
I get this error:

<img width="1081" alt="GitHub_Story_Points_-_Chrome_Web_Store" src="https://user-images.githubusercontent.com/2114187/58096288-ec6d3380-7bfe-11e9-8609-1f629938e25d.png">

Browser: chrome version 74.0.3729.157 (Official Build) (64-bit) OSX

**Comment by banyan** [comment]
Thanks! 🙇 @agungyuliaji 
now it should be fixed. 0.2.4 should be fixed. (it will take an hour to update in chrome store)
