### ISSUE TITLE
Enable on GitHub Enterprise hostings

### ISSUE THREAD

**Issue by koppor** [banyan/github-story-points#8]
Is it possible to enable this extension for a GitHub enterprise hosting, too?

[Refined-Github](https://github.com/sindresorhus/refined-github) can also be enabled on GitHub enterprise:

![image](https://user-images.githubusercontent.com/1366654/61063947-25f13c80-a401-11e9-96a6-5f0af37965b2.png)

**Comment by banyan** [comment]
@koppor 

Thanks! I can handle when I have time. also pull request is welcome! 👍

**Comment by fregante** [comment]
I recently published 2 modules that might help you with this:


https://github.com/fregante/webext-domain-permission-toggle
https://github.com/fregante/webext-dynamic-content-scripts

You'd just need:


```sh
npm i webext-domain-permission-toggle webext-dynamic-content-scripts
```

```js
// in background.js
import 'webext-dynamic-content-scripts';
import addDomainPermissionToggle from 'webext-domain-permission-toggle';

addDomainPermissionToggle();
```

And some adjustments to manifest.json

**Comment by banyan** [comment]
@fregante 

Thanks for the info!!

**Comment by banyan** [comment]
Applied https://github.com/banyan/github-story-points/issues/8#issuecomment-519218680. (Thanks @fregante for great library!!) 

![image](https://user-images.githubusercontent.com/19625/62818473-9fa45380-bb82-11e9-83c4-0f29b5b75bb3.png)

@koppor would you check if this works on your GHE environment?

**Comment by fregante** [comment]
Here you'll also find more about how it works by the way https://stackoverflow.com/a/57381191/288906

**Comment by koppor** [comment]
Works great. Thank you for the quick reaction!

**Comment by fregante** [comment]
Good to hear!
